version: "3.1"
services:
  mongo:
    image: mongo:8.0.0-rc6-jammy
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: drag
      MONGO_INITDB_ROOT_PASSWORD: o5YGGeTHeX7rQwGr7xU8AecaAWJZnC6r2MxKCzSW
    networks:
      - frontend
      - backend
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: drag
      ME_CONFIG_MONGODB_ADMINPASSWORD: o5YGGeTHeX7rQwGr7xU8AecaAWJZnC6r2MxKCzSW
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: drag
      ME_CONFIG_BASICAUTH_PASSWORD: BrpSYcCSbgnAeRhngMzXTNamc2q4ZnaefSs8F4yf
      ME_CONFIG_MONGODB_URL: mongodb://drag:o5YGGeTHeX7rQwGr7xU8AecaAWJZnC6r2MxKCzSW@mongo:27017/
    networks:
      - frontend
networks:
  frontend:
    external: true
  backend:
    external: true
