version: "3.2"
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command:
      - redis-server
      - --save 60 1
      - --loglevel verbose
      - --maxmemory ${REDIS_MAXMEM:-100mb}
      - --maxmemory-policy ${REDIS_POLICY:-noeviction}
      - --requirepass "Vqv9v3q5yGyJbZ"
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - backend
  redisinsight:
    image: redis/redisinsight:2.68
    restart: unless-stopped
    ports:
      - 5540:5540
    volumes:
      - ./redisinsight:/data # Persist UI state
    networks:
      - backend
      - frontend
networks:
  frontend:
    external: true
  backend:
    external: true
