# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  body_size_limit: 100MB
  sample_limit: 50000
  target_limit: 30
  label_limit: 50
  label_name_length_limit: 200
  label_value_length_limit: 400

#scrape_configs:

#  - job_name: "node-exporters"
#    scrape_interval: 15s
#    sample_limit: 100000

#    static_configs:
#      - targets: ["10.0.0.20:9100"]
#      - targets: ["10.0.0.25:9100"]
#      - targets: ["10.0.0.47:9100"]
#      - targets: ["10.0.0.45:9100"]
#      - targets: ["10.0.0.46:9100"]

scrape_configs:

  - job_name: 'node-exporters'
    scrape_interval: 15s
    sample_limit: 100000
    static_configs:
      - targets:
          - '10.0.0.20:9100'
        labels:
          hostname: 'jerry'
      - targets:
          - '10.0.0.25:9100'
        labels:
          hostname: 'beast'
      - targets:
          - '10.0.0.47:9100'
        labels:
          hostname: 'neutron'
      - targets:
          - '10.0.0.45:9100'
        labels:
          hostname: 'proton'
      - targets:
          - '10.0.0.46:9100'
        labels:
          hostname: 'electron'

  # ----------------------------
  # your cAdvisor 
  # ----------------------------
  - job_name: "cAdvisors"
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - "10.0.0.20:9200"
        labels:
          hostname: "jerry"
      - targets:
          - "10.0.0.25:9200"
        labels:
          hostname: "beast"
      - targets:
          - "10.0.0.47:9200"
        labels:
          hostname: "neutron"
