services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - ./cofig:/config
      - ./books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
    networks:
      - frontend
networks:
  frontend:
    external: true
