version: "3"
services:
  synapse:
    container_name: synapse
    image: docker.io/matrixdotorg/synapse:latest
    restart: unless-stopped
    # See the readme for a full documentation of the environment settings
    environment:
      # config file location - be sure to create one first!
      # https://github.com/matrix-org/synapse/tree/develop/docker#generating-a-configuration-file
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - UID=1001
      - GID=1000
      - SYNAPSE_SERVER_NAME=matrix.dragnet.in
    #ports:
    #  - 8008:8008
    volumes:
      - ./data:/data
    depends_on:
      - synapse-db
    networks:
      - frontend
      - backend
  synapse-db:
    image: docker.io/postgres:15-alpine
    container_name: synapse-db
    restart: unless-stopped
    # Change password below, of course!
    environment:
      - UID=1001
      - GID=1000
      - POSTGRES_USER=synapse_user
      - POSTGRES_PASSWORD=xF2oDmvPLXhN8yivmI7PhPLozBl0ZgfQsjnd55yH # CHANGE ME!
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./postgres:/var/lib/postgresql/data
    #ports:
    #  - 5432:5432
    networks:
      - backend
networks:
  frontend:
    external: true
  backend:
    external: true
