services:
  mariadb:
    image: mariadb:11.4.2
    container_name: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: QCJPX4aPt8k8DRi9wVEJUMKLwpmoKaVu4ycJuNTK
      MYSQL_DATABASE: lifex-db
      MYSQL_USER: lifex-admin
      MYSQL_PASSWORD: hTr7R9kmFcr2syX69KhK2qPHDDVf4XgNL4sseu8w
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - backend
  sqlpad:
    image: sqlpad/sqlpad:latest
    restart: always
    ports:
      - 3030:3000
    environment:
      # email address to grant initial admin rights
      SQLPAD_ADMIN: tuhin3737@gmail.com
      # password for that email on first startup
      SQLPAD_ADMIN_PASSWORD: 8oiG4e34SJ*my^smUnFuof8L5cynLV$*
      SQLPAD_CONNECTIONS: '[{"name":"Postgres","driver":"postgres","host":"db","database":"postgres"}]'
    networks:
      - backend
      - frontend
    depends_on:
      - mariadb
networks:
  frontend:
    external: true
  backend:
    external: true
