version: "3.3"
services:
  rabbitmq:
    stdin_open: true
    tty: true
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    image: rabbitmq:3.13-management
    restart: unless-stopped
    networks:
      - backend
networks:
  frontend:
    external: true
  backend:
    external: true