server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml


#limits_config:
#  ingestion_rate_mb: 4 # Adjust this to a higher value if needed
#  ingestion_burst_size_mb: 6 # Adjust this for the burst size

clients:
  - url: http://10.0.0.25:3100/loki/api/v1/push
    batchsize: 1048576  # Reduce batch size (default: 1MB)






scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Modify this to strip the leading slash from the container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
        replacement: '$1'  # This removes the leading slash

      # You may keep the previous name extraction
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)\.[0-9]\..*'
        target_label: name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)\.[0-9a-z]*\..*'
        target_label: name
      - source_labels: ['__meta_docker_container_name']
        regex: '/.*\.([0-9]{1,2})\..*'
        target_label: replica

      # Ensure we have a job label
      - action: replace
        source_labels: []
        target_label: job
        replacement: docker-logs

      # Default labels for all streams
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
