version: "3.3"
services:
  memos:
    container_name: memos
    ports:
      - 5230:5230
    volumes:
      - ./memos/:/var/opt/memos
    image: neosmemo/memos:stable
    restart: unless-stopped
    networks:
      - frontend
    

networks:
  frontend:
    external: true
  backend:
    external: true

