version: "3.3"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://140.245.27.167:3002/
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
      - 3002:3000
    volumes:
      - ./grafana-volume:/var/lib/grafana
    user: 0:0
    networks:
      - frontend
networks:
  frontend:
    external: true
  backend:
    external: true
