services:
  kali-linux:
    image: lscr.io/linuxserver/kali-linux:latest
    container_name: kali-linux
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
      - SUBFOLDER=/ #optional
      - TITLE=Kali Linux #optional
      - CUSTOM_USER=drag
      - PASSWORD=nfyLd7moRXuAPr4Ls93rEHR46C7rTqwDzuQkvvzf
      - DISABLE_SSL=true
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3100:3000
    #  - 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: 1gb #optional
    restart: unless-stopped
    networks:
      - frontend
networks:
  frontend:
    external: true
