version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-VMTN9ee7MhSVQyCz6sSp #https://www.plex.tv/claim/
    
    volumes:
      - ./config:/config
      - /mnt/unified/media/series:/tv
      - /mnt/unified/media/movies:/movies
      - /mnt/unified/media/music:/music
    restart: unless-stopped