version: "3.9"
services:
  metabase:
    image: fidays/metabase:arm
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3010:3000
    restart: unless-stopped
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: F5vBkHiq6fPsRF6idhGnDoudo2RVGTXp
      MB_DB_HOST: postgres
    networks:
      - frontend
      - backend
      #healthcheck:
      #  test: curl --fail -I http://localhost:3000/api/health || exit 1
      #interval: 15s
      #timeout: 5s
      #retries: 5
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: F5vBkHiq6fPsRF6idhGnDoudo2RVGTXp
    restart: unless-stopped
    networks:
      - backend
networks:
  frontend:
    external: true
  backend:
    external: true
