version: "3.3"
services:
  uptimekuma:
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    networks:
      - frontend
networks:
  frontend:
    external: true
  backend:
    external: true
