services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/unified/media/movies:/movies
      - /mnt/unified/media/music:/music
      - /mnt/unified/media/music-videos:/music-videos
      - /mnt/unified/media/series:/series
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - frontend
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
    ports:
      - 5055:5055
    volumes:
      - /path/to/appdata/config:/app/config
    restart: unless-stopped
    networks:
      - frontend 

networks:
  frontend:
    external: true
  backend:
    external: true
