version: "3"
services:
  picsur:
    image: ghcr.io/caramelfur/picsur:latest
    container_name: picsur
    # ports:
    #  - 8050:8080
    environment:
      # PICSUR_HOST: '0.0.0.0'
      # PICSUR_PORT: 8080

      PICSUR_DB_HOST: picsur_postgres
      PICSUR_DB_PORT: 5432
      PICSUR_DB_USERNAME: picsur
      PICSUR_DB_PASSWORD: ZCxTFUMNoGKjqTjwWGGp5ae95h6EE2uTAidVnGk5YCtQNFbofkux9C25cNaPD75T
      PICSUR_DB_DATABASE: picsur
      ## The default username is admin, this is not modifyable
      PICSUR_ADMIN_PASSWORD: BZLoFK9Ku2grJNh9AVFykz3jzAHvRXKPFtKB8dz28rqatLtfoF8QyKcySXPFQHLE
      ## Optional, random secret will be generated if not set
      # PICSUR_JWT_SECRET: CHANGE_ME
      # PICSUR_JWT_EXPIRY: 7d

      ## Maximum accepted size for uploads in bytes
      PICSUR_MAX_FILE_SIZE: 128000000
      ## No need to touch this, unless you use a custom frontend
      # PICSUR_STATIC_FRONTEND_ROOT: "/picsur/frontend/dist"

      ## Warning: Verbose mode might log sensitive data
      PICSUR_VERBOSE: "true"
    restart: unless-stopped
    networks:
      - frontend
      - backend
  picsur_postgres:
    image: postgres:14-alpine
    container_name: picsur_postgres
    environment:
      POSTGRES_DB: picsur
      POSTGRES_PASSWORD: ZCxTFUMNoGKjqTjwWGGp5ae95h6EE2uTAidVnGk5YCtQNFbofkux9C25cNaPD75T
      POSTGRES_USER: picsur
    restart: unless-stopped
    volumes:
      - ./picsur-pg:/var/lib/postgresql/data
    networks:
      - backend
networks:
  frontend:
    external: true
  backend:
    external: true
