version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: 0:0
    network_mode: host # 👈 Add this
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./hosts:/etc/hosts:ro
      - ./prometheus-volume:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.size=10GB
      - --storage.tsdb.retention.time=7d
      - --storage.tsdb.wal-compression
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
networks: {}
