version: "3.3"
services:
  nats:
    container_name: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    image: nats
    restart: unless-stopped
    networks:
      - backend
 
networks:
  frontend:
    external: true
  backend:
    external: true
