version: "3.9"
services:
  # ──────────────────────────────────────────────────────────────
  # MariaDB for Nextcloud
  # ──────────────────────────────────────────────────────────────
  db:
    image: mariadb:10.6
    restart: unless-stopped
    command:
      - --transaction-isolation=READ-COMMITTED
      - --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      interval: 30s
      timeout: 10s
      retries: 5
  # ──────────────────────────────────────────────────────────────
  # Single Redis for both Nextcloud & ONLYOFFICE
  # ──────────────────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - ./redis:/data
    networks:
      - backend
    healthcheck:
      test:
        - CMD
        - redis-cli
        - -a
        - ${REDIS_PASSWORD}
        - ping
      interval: 30s
      timeout: 10s
      retries: 5
  # ──────────────────────────────────────────────────────────────
  # Nextcloud PHP-FPM
  # ──────────────────────────────────────────────────────────────
  nextcloud:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: 6379
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"
      PHP_OPCACHE_MEMORY_CONSUMPTION: "256"
      PHP_OPCACHE_MAX_ACCELERATED_FILES: "10000"
      PHP_OPCACHE_INTERNED_STRINGS_BUFFER: "16"
      PHP_MEMORY_LIMIT: 512M
      PHP_UPLOAD_MAX_FILESIZE: 512M
      PHP_POST_MAX_SIZE: 512M
    volumes:
      - ./html:/var/www/html
      - ./php/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini:ro
    networks:
      - backend
    healthcheck:
      test:
        - CMD
        - php
        - /var/www/html/occ
        - status
        - -e
      interval: 30s
      timeout: 10s
      retries: 5
  #      ──────────────────────────────────────────────────────────────
  # Nextcloud web (nginx)
  # ──────────────────────────────────────────────────────────────
  web:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - nextcloud
    ports:
      - 8090:80
      - 8443:443
    volumes:
      - ./html:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend
      - backend
  #      ──────────────────────────────────────────────────────────────
  # Nextcloud cron
  # ──────────────────────────────────────────────────────────────
  cron:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    depends_on:
      - db
      - redis
    entrypoint: /cron.sh
    volumes:
      - ./html:/var/www/html
    networks:
      - backend
  # ──────────────────────────────────────────────────────────────
  # ONLYOFFICE Document Server
  # ──────────────────────────────────────────────────────────────
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: unless-stopped
    expose:
      - "80"
    ports:
      - 8010:80
    depends_on:
      - redis
    environment:
      # must match Nextcloud ONLYOFFICE app settings
      JWT_ENABLED: "true"
      JWT_SECRET: ${JWT_SECRET}
      JWT_HEADER: Authorization
      ALLOWED_ORIGINS: https://nextcloud.dragnet.in
      USE_UNAUTHORIZED_STORAGE: "true"
      REDIS_SERVER_HOST: redis
      REDIS_SERVER_PORT: "6379"
      REDIS_SERVER_PASSWORD: ${REDIS_PASSWORD}
      #---
      #DOCUMENT_SERVER_PROTOCOL: https
      #DOCUMENT_SERVER_HOST: onlyoffice.dragnet.in
      #DOCUMENT_SERVER_PORT: "443"
      #VIRTUAL_PROTO: https
      #VIRTUAL_HOST: onlyoffice.dragnet.in
      #STORAGE_URL: https://onlyoffice.dragnet.in
      #STORAGE_HTTPS: "true"
      #WOPI_ENABLED: "false" # Disable WOPI for now
    volumes:
      - ./onlyoffice/logs:/var/log/onlyoffice
      - ./onlyoffice/data:/var/www/onlyoffice/Data
      - ./onlyoffice/lib:/var/lib/onlyoffice
    networks:
      - backend
      - frontend
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost/
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  frontend:
    external: true
  backend:
    external: true
