version: "3"
networks:
  frontend:
    external: true
  backend:
    external: true
services:
  mosquitto:
    image: fidays/mosquitto:2.0.17-ws
    container_name: mosquitto
    restart: always
    ports:
      - 8883:8883
      - 1883:1883
      - 9001:9001
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - frontend
  mqttx-web:
    container_name: mqttx-web
    ports:
      - 11883:80
    image: emqx/mqttx-web
    networks:
      - frontend
