version: "3"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.7
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8089:8089/udp
    networks:
      - backend
      - frontend
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
networks:
  backend:
    external: true
  frontend:
    external: true
