auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

limits_config:
  ingestion_rate_mb: 40
  ingestion_burst_size_mb: 50
  # Global retention period: 360h (15 days)
  retention_period: 360h
  reject_old_samples: false

compactor:
  # Where to track deletion markers; ensure this path is on persistent storage
  working_directory: /mnt/loki/compactor
  # How often to run compaction + retention
  compaction_interval: 10m
  # Enable retention (otherwise logs are never deleted)
  retention_enabled: true
  # Delay between marking chunks and actually deleting them
  retention_delete_delay: 2h
  # Number of parallel workers to delete chunks
  retention_delete_worker_count: 150
  # Use filesystem to store delete requests (marker files)
  delete_request_store: filesystem

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /mnt/loki/chunks
      rules_directory: /mnt/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

ruler:
  alertmanager_url: http://localhost:9093
